### ISSUE TITLE
Add screenshot in readme

### ISSUE THREAD

**Issue by codeallthethingz** [groupby/dash#5]

**Comment by effervescentia** [comment]
<img width="948" alt="screen shot 2016-09-13 at 09 39 11" src="https://cloud.githubusercontent.com/assets/3784470/18475925/3b3396e4-7996-11e6-9457-5af30720a46d.png">

**Comment by effervescentia** [comment]
<img width="941" alt="screen shot 2016-09-13 at 09 43 38" src="https://cloud.githubusercontent.com/assets/3784470/18476055/9d093ad6-7996-11e6-8417-dde80ae1ef45.png">
